# Exported from Render on 2025-12-06T18:50:37Z
version: "1"
projects:
- name: min-monorepo-project-dec2025
  environments:
  - name: Production
    services:
    - type: web
      name: min-monorepo-fe-dec2025
      runtime: static
      repo: https://github.com/ngsiokun/min-monorepo
      branch: main
      buildCommand: npm run build
      staticPublishPath: ./dist
      autoDeployTrigger: commit
      rootDir: frontend
    - type: web
      name: min-monorepo-be-dec2025
      runtime: python
      repo: https://github.com/ngsiokun/min-monorepo
      branch: main
      plan: free
      envVars:
      - key: ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        fromService: # Copy frontend URL for CORS configuration
          type: web
          name: min-monorepo-fe-dec2025
          envVarKey: RENDER_EXTERNAL_URL
      region: singapore
      buildCommand: uv sync --no-dev
      startCommand: uv run main.py
      healthCheckPath: /health
      autoDeployTrigger: commit
      rootDir: backend